<?php

use Illuminate\Database\Seeder;
use App\Models\Service;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $service_names = [
            'Piscina',
            'Wi-fi',
            'Wi-fi veloce e affidabile',
            'Tv',
            'Cucina',
            'Cucina completamente accessoriata',
            'Piano cottura a induzione in acciaio inox',
            'Piatti e posate',
            'Frigorifero',
            'Frigobar',
            'Freezer',
            'Forno a microonde',
            'Forno',
            'Forno in acciaio inossidabile',
            'Servizi di base per cucinare',
            'Piatti e posate',
            'Lavastoviglie',
            'Bollitore',
            'Macchina del caffè',
            'Tostapane',
            'Frullatore',
            'Colazione',
            'Teglia da forno',
            'Barbecue',
            'Utensili da barbecue',
            'Tavolo da pranzo',
            'Parcheggio gratuito in strada',
            'Parcheggio privato',
            'Parcheggio a pagamento non in loco',
            'Garage',
            'Ascensore',
            'Vasca idromassaggio',
            'Asciugacapelli',
            'Lavatrice',
            'Asciugatrice',
            'Aria condizionata',
            'Riscaldamento',
            'Climatizzatore centralizzato',
            'Camino',
            'Riscaldamento centralizzato',
            'Doccia',
            'Bidet',
            'Acqua calda',
            'Self check-in',
            "L'host ti accoglie di persona",
            'Zona lavoro computer-friendly',
            'Animali domestici ammessi',
            'Animali domestici non ammessi',
            'Rilevatore di monossido di carbonio',
            'Allarme antifurto',
            'Allarme antincendio',
            'Rilevatore di fumo',
            'Estintore',
            'Kit di pronto soccorso',
            'Piano e numeri telefonici di emergenza',
            'Telecamere di sicurezza',
            'Ingresso senza gradini',
            'Ingressi ampi (almeno 81,3 cm)',
            'Corridoi ampi (almeno 91,5 cm)',
            'Bagno accessibile',
            'Carta igienica, lenzuola e asciugamani in più',
            'Shampoo e balsamo',
            'Sapone per piatti e prodotti per la pulizia',
            'Bicchieri da vino',
            'Grucce appendiabiti',
            "Spazio per conservare l'abbigliamento: guardaroba",
            'Letto singolo',
            'Letto matrimoniale',
            'Divano letto',
            'Biancheria da letto',
            'Ferro da stiro',
            'Cuscini e coperte extra',
            'Cassaforte',
            'Cassetta di sicurezza',
            'Adattatori e caricabatterie',
            'Buona illuminazione',
            'Culla e seggiolone',
            'Baby monitor',
            'Fasciatoio',
            'Vasca da bagno',
            'Fodere e teli per arredi',
            'Ciotole per cibo e acqua per animali domestici',
            'Ottima posizione',
            'Vista sul mare',
            'Vista sul lago',
            'Vista sulla baia',
            'Vista sulle montagne',
            'Vista sul giardino',
            'Ingresso privato',
            'Accesso alla spiaggia',
            'Accesso al lago',
            'Cortile privato',
            'Cortile privato (Completamente recintato)',
            'Patio o balcone privata',
            'Arredi da esterni',
            "Zona pranzo all'aperto",
            'Cancellazione gratuita',
            'Vicino alla stazione del treno',
            'Vicino alla stazione dei bus',
            "Vicino all'aeroporto",
            "Base per fuoco all'aperto",
            'Tende oscuranti',
            'Zanzariera',
            'Attrezzatura sportiva',
            'Libri e materiale di lettura',
            'Compattatore di rifiuti',
        ];


        foreach ($service_names as $name) {
            $service = new Service();
            $service->name = $name;
            $service->save();
        }
    }
}
